name: CI on Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "gcc12 (c++23)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11 (c++23)"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc10 (c++20)"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "clang14 (c++23)"
            cxx: "clang++-14"
            cc: "clang-14"
            build_type: Release
            cxx_flags: "-std=c++2b"

          - name: "clang13 (c++23)"
            cxx: "clang++-13"
            cc: "clang-13"
            build_type: Release
            cxx_flags: "-std=c++2b"

          - name: "clang12 (c++20)"
            cxx: "clang++-12"
            cc: "clang-12"
            build_type: Release
            cxx_flags: "-std=c++20"

    steps:
      - name: Standard SeqAn2 App testing
        uses: seqan/actions@test/seqan2_v11
        with:
          name: ${{ matrix.name }}
          cc: ${{ matrix.cc }}
          cxx: ${{ matrix.cxx }}
          cxx_flags: "${{ matrix.cxx_flags }}  -Wextra -Werror"
          build_type: ${{ matrix.build_type }}
