name: CI on macOS

on:
  push:
    branches:
      - 'main'
  pull_request:
  # Enables a manual trigger, may run on any branch
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CMAKE_VERSION: 3.15.0
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 180
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "gcc12 (c++23)"
            cxx: "g++-12"
            cc: "gcc-12"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc11 (c++23)"
            cxx: "g++-11"
            cc: "gcc-11"
            build_type: Release
            cxx_flags: "-std=c++23"

          - name: "gcc10 (c++20)"
            cxx: "g++-10"
            cc: "gcc-10"
            build_type: Release
            cxx_flags: "-std=c++20"

          - name: "clang13 (c++23)"
            cxx: "clang++-13"
            cc: "clang-13"
            build_type: Release
            cxx_flags: "-std=c++2b"

          - name: "clang12 (c++23)"
            cxx: "clang++-12"
            cc: "clang-12"
            build_type: Release
            cxx_flags: "-std=c++2b"

          - name: "clang11 (c++20)"
            cxx: "clang++-11"
            cc: "clang-11"
            build_type: Release
            cxx_flags: "-std=c++20"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: repo
          fetch-depth: 2
          submodules: true

      - name: Checkout SeqAn3
        uses: actions/checkout@v3
        with:
          repository: seqan/seqan3
          ref: 39e696830bbdcde0e520c87811db3eb5e083d7c0
          path: seqan3
          fetch-depth: 2
          submodules: false

      - name: Configure Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install CMake
        run: bash ./seqan3/.github/workflows/scripts/install_cmake.sh

      - name: Install ccache
        run: bash ./seqan3/.github/workflows/scripts/install_via_brew.sh ccache

      - name: Install compiler ${{ matrix.cxx }}
        env:
          CC: ${{ matrix.cc }}
        run: bash ./seqan3/.github/workflows/scripts/install_via_brew.sh $(echo ${CC/clang/llvm} | awk -F '-' '{print $1, $2}')

      - name: Tool versions
        run: |
          env cmake --version
          env ${{ matrix.cxx }} --version
          sudo xcode-select -s '/Applications/Xcode_13.4.1.app/Contents/Developer' # https://github.com/actions/runner-images/issues/6350

      - name: Install dependencies
        run: brew install --force-bottle boost

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Load ccache
        uses: actions/cache@v3
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}-${{ github.run_number }}
          # Restoring: From current branch, otherwise from base branch, otherwise from any branch.
          restore-keys: |
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-${{ github.base_ref }}
            ${{ runner.os }}-${{ matrix.name }}-ccache-

      - name: Configure tests
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir build
          cd build
          cmake ../repo -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                        -DCMAKE_CXX_FLAGS="${{ matrix.cxx_flags }} -Wextra -Werror" \
                        -DSEQAN_DISABLE_VERSION_CHECK=ON \
                        -DSEQAN_GH_ACTIONS_BUILD:BOOL=ON \
                        -DPython3_ROOT_DIR=${pythonLocation} \
                        -DPython3_EXECUTABLE=${pythonLocation}/bin/python3 \
                        -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build tests
        env:
          CCACHE_BASEDIR: ${{ github.workspace }}
          CCACHE_DIR: ${{ github.workspace }}/.ccache
          CCACHE_COMPRESS: true
          CCACHE_COMPRESSLEVEL: 6
          CCACHE_MAXSIZE: 200M
        run: |
          cd build
          make -k -j3

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure --timeout 240 || ctest . -j3 --output-on-failure --timeout 240 --rerun-failed
